name: Telegram Bot Test

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repository-ni yüklə
        uses: actions/checkout@v4

      - name: Python qur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Kitabxanaları quraşdır
        run: pip install -r requirements.txt

      - name: Telegram botunu başlad
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python telegram_bot.py
